const title=document.querySelector('.hero-title');
title.querySelectorAll('.title-line').forEach((target,n)=>{const line=target.textContent;target.textContent='';[...line].forEach((char,i)=>{const span=document.createElement('span');span.className='char';span.textContent=char;span.style.animationDelay=`${(n*5+i)*.08}s`;target.appendChild(span)})});
const header=document.querySelector('.site-header'),menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav-links');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.13});document.querySelectorAll('.reveal').forEach((el,i)=>{if(el.classList.contains('interest'))el.style.transitionDelay=`${i*.1}s`;observer.observe(el)});
const canvas=document.querySelector('#particle-canvas'),ctx=canvas.getContext('2d');let particles=[],mouse={x:-1000,y:-1000};function resize(){canvas.width=innerWidth;canvas.height=innerHeight}function seed(){particles=Array.from({length:innerWidth<600?26:70},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.6+.45,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,alpha:Math.random()*.18+.06}))}function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);particles.forEach(p=>{const dx=mouse.x-p.x,dy=mouse.y-p.y,d=Math.hypot(dx,dy);if(d<130&&d>0){p.x-=dx/d*.4;p.y-=dy/d*.4}p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>canvas.width)p.vx*=-1;if(p.y<0||p.y>canvas.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=`rgba(189,114,93,${p.alpha})`;ctx.fill()});requestAnimationFrame(animate)}addEventListener('resize',()=>{resize();seed()});addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY},{passive:true});resize();seed();animate();
const track=document.querySelector('.photo-track'),slides=[...document.querySelectorAll('.photo-slide')],dots=[...document.querySelectorAll('.carousel-dots button')],prev=document.querySelector('.carousel-prev'),next=document.querySelector('.carousel-next');let currentSlide=0;function showSlide(index){currentSlide=(index+slides.length)%slides.length;track.style.transform=`translateX(-${currentSlide*100}%)`;dots.forEach((dot,i)=>dot.classList.toggle('active',i===currentSlide))}dots.forEach((dot,i)=>dot.addEventListener('click',()=>{showSlide(i);resetCarousel()}));prev.addEventListener('click',()=>{showSlide(currentSlide-1);resetCarousel()});next.addEventListener('click',()=>{showSlide(currentSlide+1);resetCarousel()});let carouselTimer=setInterval(()=>showSlide(currentSlide+1),4200);function resetCarousel(){clearInterval(carouselTimer);carouselTimer=setInterval(()=>showSlide(currentSlide+1),4200)}
const botToggle=document.querySelector('.chatbot-toggle'),chatWindow=document.querySelector('.chat-window'),chatClose=document.querySelector('.chat-close'),chatMessages=document.querySelector('.chat-messages'),chatForm=document.querySelector('.chat-form'),chatInput=document.querySelector('#chat-input'),keyInput=document.querySelector('#gemini-key'),saveKey=document.querySelector('#save-key');const aboutMe=document.querySelector('main').innerText;let chatHistory=[];keyInput.value=localStorage.getItem('migoGeminiKey')||'';function closeChat(){if(!chatWindow.classList.contains('open'))return;chatWindow.classList.remove('open');chatWindow.classList.add('closing');setTimeout(()=>chatWindow.classList.remove('closing'),600)}botToggle.addEventListener('click',e=>{e.stopPropagation();chatWindow.classList.remove('closing');chatWindow.classList.toggle('open')});chatClose.addEventListener('click',closeChat);document.addEventListener('click',e=>{if(chatWindow.classList.contains('open')&&!chatWindow.contains(e.target)&&!botToggle.contains(e.target))closeChat()});saveKey.addEventListener('click',()=>{localStorage.setItem('migoGeminiKey',keyInput.value.trim());saveKey.textContent='已儲存';setTimeout(()=>saveKey.textContent='儲存',1500)});function addMessage(text,type){const bubble=document.createElement('div');bubble.className=`chat-message ${type}`;bubble.textContent=text;chatMessages.appendChild(bubble);chatMessages.scrollTop=chatMessages.scrollHeight;return bubble}function addTyping(){const bubble=document.createElement('div');bubble.className='chat-message bot chat-typing';bubble.innerHTML='<i></i><i></i><i></i>';chatMessages.appendChild(bubble);chatMessages.scrollTop=chatMessages.scrollHeight;return bubble}chatForm.addEventListener('submit',async e=>{e.preventDefault();const question=chatInput.value.trim(),apiKey=keyInput.value.trim()||localStorage.getItem('migoGeminiKey');if(!question)return;if(!apiKey){addMessage('請先在下方輸入你的 Gemini API Key，再來問我喔！','bot');return}addMessage(question,'user');chatInput.value='';const typing=addTyping();chatHistory.push({role:'user',parts:[{text:question}]});try{const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:`你是「米糕的 24/7 個人助理」。請只根據以下資料回答關於米糕的問題：${aboutMe}。請使用繁體中文，語氣親切自然；如果問題與米糕無關，請誠實說明你主要是介紹米糕，不要捏造資料。回答簡潔但有內容。`}]},contents:chatHistory,generationConfig:{temperature:.7,maxOutputTokens:500}})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`HTTP ${response.status}`);const answer=data.candidates?.[0]?.content?.parts?.[0]?.text||'我剛剛沒有收到完整回答，再問我一次好嗎？';typing.remove();addMessage(answer,'bot');chatHistory.push({role:'model',parts:[{text:answer}]})}catch(error){typing.remove();addMessage(`連線失敗：${error.message}`,'bot')}});
const resumeSection=document.querySelector('#resume');
if(resumeSection){
  const timeline=resumeSection.querySelector('.resume-timeline');
  if(timeline){[...timeline.children].sort((a,b)=>{const getScore=el=>{const text=el.querySelector('.resume-time')?.textContent||'';const ongoing=text.includes('迄今');const dates=[...text.matchAll(/(\d{4})\.(\d{2})/g)].map(match=>Number(`${match[1]}${match[2]}`));return {ongoing,latest:dates.at(-1)||0,start:dates[0]||0}};const first=getScore(a),second=getScore(b);if(first.ongoing!==second.ongoing)return Number(second.ongoing)-Number(first.ongoing);if(first.latest!==second.latest)return second.latest-first.latest;return second.start-first.start}).forEach(item=>timeline.appendChild(item))}
  resumeSection.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i*.06,.3)}s`;observer.observe(el)});
}
const contactForm=document.querySelector('#contact-form');
if(contactForm){const contactSubmit=contactForm.querySelector('.contact-submit'),formStatus=contactForm.querySelector('#form-status'),defaultLabel=contactSubmit.textContent;contactForm.addEventListener('submit',async event=>{event.preventDefault();if(!contactForm.checkValidity()){contactForm.reportValidity();return}contactSubmit.disabled=true;contactSubmit.textContent='送出中…';contactForm.setAttribute('aria-busy','true');formStatus.textContent='';formStatus.className='form-status';try{const response=await fetch(contactForm.action,{method:'POST',body:new FormData(contactForm),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Formspree request failed');contactForm.reset();formStatus.textContent='收到了！我會盡快回你';formStatus.className='form-status success'}catch(error){formStatus.textContent='好像出了點問題，可以再試一次，或直接寄信到 seanden116@gmail.com';formStatus.className='form-status error'}finally{contactSubmit.disabled=false;contactSubmit.textContent=defaultLabel;contactForm.removeAttribute('aria-busy')}})}
